[connections.snowflake]
account = "CDTLSLB-BZB78899"
user = "sethfeldman99"
password = "N0fuck!ngway"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
