[connections.snowflake]
account = "https://avb05691.snowflakecomputing.com"
user = "SethFeldman99"
password = "D0nt3ventry1t"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
