[connections.snowflake]
account = "CDTLSLB-BZB78899"
user = "SethFeldman99"
password = "D0nt3ventry1t"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
